[package]
name = "graphql-ws"
version = "0.1.0"
authors = ["Gordon Guan <admin@netdex.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.9"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread", "sync"] }
tokio-tungstenite = { version = "0.14" }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
tokio-stream = { version = "0.1.5", features = ["sync"] }
futures = "0.3"
