[package]
name = "vulcan-relay"
version = "0.1.0"
authors = ["netdex"]
edition = "2018"

[dependencies]
mediasoup = "0.7.1"

log = "0.4.14"
env_logger = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
serde_repr = "0.1.6"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

thiserror = "1.0"
anyhow = "1.0"
event-listener-primitives = "0.2.2"
clap = "3.0.0-beta.2"

tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.5", features = ["sync"] }
tokio-local = { path = "tokio-local" }
futures = "0.3"
async-stream = "0.3.0"
async-trait = "0.1.48"

warp = { version = "0.3", features = ["tls"] }
async-graphql = "2.8.4"
async-graphql-warp = "2.8.4"

[dev-dependencies]
actix = "0.10.0"
actix-web = { version = "3.3.2", features = ["openssl"] }
actix-web-actors = "3.0.0"
openssl = { version = "0.10", features = ["v110"] }

[workspace]
members = [
    "tokio-local"
]