name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup component add rustfmt
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - run: rustup component add clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Test Suite
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Check out schema
        uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          repository: "vulcan-fydp/schema"
          ref: master
          token: ${{ secrets.VULCAN_FYDP_CI_GH_PAT }}
          path: "./schema"
      - name: Dump schema
        if: github.event_name == 'push'
        run: |
          cargo run --bin dump_control_schema > ./schema/control_schema.gql
          cargo run --bin dump_signal_schema > ./schema/signal_schema.gql
      - name: Commit schema if changed
        if: github.event_name == 'push'
        working-directory: ./schema
        run: |
          if [[ `git status --porcelain` ]]; then
            cd ..
            python ./schema/update-version.py
            cd schema
            VERSION=`cat ./version`

            git config user.email "vulcanfydp@gmail.com"
            git config user.name "Vulcan Fydp"
            git commit -am "Update relay schema to v$VERSION"
            git tag -a v$VERSION -m v$VERSION
            git push origin master --follow-tags
          fi
